"""buat tabel admin

Revision ID: 2cf20793a788
Revises: e55c0b0d4e05
Create Date: 2023-09-13 03:15:58.644192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf20793a788'
down_revision = 'e55c0b0d4e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('ID_Admin', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('NIK', sa.String(length=16), nullable=False),
    sa.Column('Nama', sa.String(length=50), nullable=False),
    sa.Column('Username', sa.String(length=20), nullable=False),
    sa.Column('Password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('ID_Admin')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
