"""buat tabel gampong

Revision ID: d309068441ab
Revises: b2a143531281
Create Date: 2023-09-13 03:33:20.803590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd309068441ab'
down_revision = 'b2a143531281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gampong',
    sa.Column('Kode_Gampong', sa.String(length=5), nullable=False),
    sa.Column('Nama_Gampong', sa.String(length=15), nullable=False),
    sa.Column('Kecamatan', sa.String(length=20), nullable=False),
    sa.Column('Dusun', sa.String(length=15), nullable=False),
    sa.Column('NIK', sa.String(length=16), nullable=False),
    sa.Column('Nama', sa.String(length=50), nullable=False),
    sa.Column('Email', sa.String(length=50), nullable=False),
    sa.Column('Nomor_HP', sa.String(length=13), nullable=False),
    sa.Column('Username', sa.String(length=20), nullable=False),
    sa.Column('Password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('Kode_Gampong')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gampong')
    # ### end Alembic commands ###
