"""buat tabel staf_BMAB

Revision ID: e55c0b0d4e05
Revises: 116491a72022
Create Date: 2023-09-13 02:46:02.654198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55c0b0d4e05'
down_revision = '116491a72022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staf_bmab',
    sa.Column('NIK', sa.String(length=16), nullable=False),
    sa.Column('Nama', sa.String(length=50), nullable=False),
    sa.Column('Email', sa.String(length=50), nullable=False),
    sa.Column('Nomor_HP', sa.String(length=13), nullable=False),
    sa.Column('Username', sa.String(length=20), nullable=False),
    sa.Column('Password', sa.String(length=20), nullable=False),
    sa.Column('Kecamatan', sa.String(length=20), nullable=False),
    sa.Column('Gampong', sa.String(length=20), nullable=False),
    sa.Column('Kode_Gampong', sa.String(length=5), nullable=False),
    sa.Column('Dusun', sa.String(length=20), nullable=False),
    sa.Column('Admin', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['Admin'], ['administator.ID_Admin'], ),
    sa.PrimaryKeyConstraint('NIK')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staf_bmab')
    # ### end Alembic commands ###
