from zaqat import db
from datetime import datetime

from zaqat.model.gampong import Gampong
from zaqat.model.staf import Staf

class Masyarakat (db.Model):
    No_KK = db.Column(db.String(16), nullable=False)
    NIK = db.Column(db.String(16), primary_key=True)
    Nama = db.Column(db.String(50), nullable=False)
    Kecamatan = db.Column(db.String(20), nullable=False)
    Nama_Gampong = db.Column(db.String(15), nullable=False)
    Kode_Gampong = db.Column(db.String(5), nullable=False)
    Tempat_Lahir = db.Column(db.String(15), nullable=False)
    #Tanggal_Lahir = db.Column(db.String(15), nullable=False)
    No_Rekening = db.Column (db.String(10), nullable=True)
    Golongan = db.Column (db.String(20), nullable=False)
    Periode = db.Column (db.String(7), nullable=True)
    Status = db.Column (db.String(7), nullable=True)
    Waktu_Input = db.Column(db.DateTime, default=datetime.utcnow)
    Waktu_Update = db.Column(db.DateTime, default=datetime.utcnow)
    Waktu_Proses = db.Column(db.DateTime, default=datetime.utcnow)    
    Dusun = db.Column(db.String(15), nullable=False)
    Admin_GP = db.Column(db.String(50), db.ForeignKey(Gampong.Nama))
    Staf_BMAB = db.Column(db.String(50), db.ForeignKey(Staf.Nama))
    #Umur = db.Column(db.String(15), nullable=False)
    Pekerjaan = db.Column(db.BigInteger, nullable=True)
    Pendapatan = db.Column(db.BigInteger, nullable=True)
    Aset = db.Column(db.BigInteger, nullable=True)
    Beban_Tanggungan = db.Column(db.BigInteger, nullable=True)
    Masa_Belajar = db.Column(db.BigInteger, nullable=True)
    Status_Insiden = db.Column(db.BigInteger, nullable=True)
    Golongan_Disabilitas = db.Column(db.BigInteger, nullable=True)
    Jenjang_Sekolah = db.Column(db.BigInteger, nullable=True)
    Umur_Muallaf = db.Column(db.BigInteger, nullable=True)
    Jlh_Hutang = db.Column(db.BigInteger, nullable=True)
    Tempo_Waktu = db.Column(db.BigInteger, nullable=True)
    #Surat_Domisili = db.Column(db.String(15), nullable=False)
    Bobot_Domisili = db.Column(db.BigInteger, nullable=True)
    #Surat_Golongan = db.Column(db.String(15), nullable=False)
    Bobot_Golongan = db.Column(db.BigInteger, nullable=True)
    #Rekening = db.Column(db.String(15), nullable=False)
    Bobot_Rekening = db.Column(db.BigInteger, nullable=True)
    #Surat_Keterangan = db.Column(db.String(15), nullable=False)
    Bobot_Keterangan = db.Column(db.BigInteger, nullable=True)
    #Jadwal_Mengajar = db.Column(db.String(15), nullable=False)
    Bobot_Jadwal = db.Column(db.BigInteger, nullable=True)
    #Surat_Keterangan2 = db.Column(db.String(15), nullable=False)
    Bobot_Keterangan2 = db.Column(db.BigInteger, nullable=True)
    #Surat_Permohonan = db.Column(db.String(15), nullable=False)
    Bobot_Permohonan = db.Column(db.BigInteger, nullable=True)
    #Kuitansi = db.Column(db.String(15), nullable=False)
    Bobot_Kuitansi = db.Column(db.BigInteger, nullable=True)
    #Paspor = db.Column(db.String(15), nullable=False)
    Bobot_Paspor = db.Column(db.BigInteger, nullable=True)
    #Ijazah = db.Column(db.String(15), nullable=False)
    Bobot_Ijazah = db.Column(db.BigInteger, nullable=True)
    #AIW = db.Column(db.String(15), nullable=False)
    Bobot_AIW = db.Column(db.BigInteger, nullable=True)
    #Izin_operasional = db.Column(db.String(15), nullable=False)
    Bobot_Izin = db.Column(db.BigInteger, nullable=True)
    #SK_Pengurus = db.Column(db.String(15), nullable=False)
    Bobot_SK = db.Column(db.BigInteger, nullable=True)
    #Data_Madrasah = db.Column(db.String(15), nullable=False)
    Bobot_Data = db.Column(db.BigInteger, nullable=True)
    #Foto_PBM = db.Column(db.String(15), nullable=False)
    Bobot_Foto = db.Column(db.BigInteger, nullable=True)